### ISSUE TITLE
Consider removing debug logging

### ISSUE THREAD

**Issue by yomed** [eBay/retriever#4]
We currently log `debug` with `r.get()` and `r.has()`. The real usefulness of logging is with `r.need`, and when users actually want to debug individual calls, they'll probably do so without the `debug` logging. There isn't much value in having the aggregate of all `debug` retriever logs for the entire application, so maybe we should just remove it.

**Comment by yomed** [comment]
Relatedly, we could add an extra param to `get()` and `has()` to optionally log a warning (since we're assuming that warnings are the real benefit here). 

```js
r.get(model, 'data', {}, isHomePage) // will only warn when isHomePage=true
```

**Comment by sidsakhadeo** [comment]
Let's do it. I really like the extra param idea. Good find @yomed
